baseURL = "https://joaopaulomcc.com/"
languageCode = "en-us"
title = "joaopaulomcc"
theme = "JP"
googleAnalytics = "UA-118399533-1"

[params]
    github = "https://github.com/joaopaulomcc/"
    linkedin = "https://www.linkedin.com/in/joaopaulomcc/"